from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterator, Mapping

from ..tool.tool_geometry import component_for_id


@dataclass(frozen=True)
class SurfaceMetadata(Mapping[str, Any]):
    """Structured metadata for a surface generated by material removal."""

    cut_range: tuple[float, float]
    normal: tuple[float, float, float] | None = None
    source: str | None = None
    grid: str | None = None
    component_id: int | None = None
    component_name: str | None = None
    surface_role: str | None = None
    component_role: str | None = None
    removed_by: str | None = None
    tool_id: str | None = None
    line_no: int | None = None
    operation_id: str | None = None
    motion_type: str | None = None
    source_line: str | None = None
    segment_index: int | None = None
    segment_count: int | None = None
    arc_center: tuple[float, float] | None = None
    arc_radius: float | None = None
    arc_direction: str | None = None
    collision_warning: bool = False
    collision_component: str | None = None
    collision_reason: str | None = None
    gouging_risk: bool = False
    sharp_edge: bool = False

    def as_dict(self) -> dict[str, Any]:
        out: dict[str, Any] = {"range": self.cut_range}
        fields = {
            "normal": self.normal,
            "source": self.source,
            "grid": self.grid,
            "component_id": self.component_id,
            "component_name": self.component_name,
            "surface_role": self.surface_role,
            "component_role": self.component_role,
            "removed_by": self.removed_by,
            "tool_id": self.tool_id,
            "line_no": self.line_no,
            "operation_id": self.operation_id,
            "motion_type": self.motion_type,
            "source_line": self.source_line,
            "segment_index": self.segment_index,
            "segment_count": self.segment_count,
            "arc_center": self.arc_center,
            "arc_radius": self.arc_radius,
            "arc_direction": self.arc_direction,
            "collision_component": self.collision_component,
            "collision_reason": self.collision_reason,
        }
        out.update({key: value for key, value in fields.items() if value is not None})
        if self.collision_warning:
            out["collision_warning"] = True
        if self.gouging_risk:
            out["gouging_risk"] = True
        if self.sharp_edge:
            out["sharp_edge"] = True
        return out

    def __getitem__(self, key: str) -> Any:
        return self.as_dict()[key]

    def __iter__(self) -> Iterator[str]:
        return iter(self.as_dict())

    def __len__(self) -> int:
        return len(self.as_dict())

    def __eq__(self, other: object) -> bool:
        if isinstance(other, SurfaceMetadata):
            return self.as_dict() == other.as_dict()
        if isinstance(other, Mapping):
            return self.as_dict() == dict(other)
        return False


def make_surface_metadata(
    cut_range: tuple[float, float],
    metadata: Mapping[str, Any] | SurfaceMetadata | None = None,
) -> SurfaceMetadata:
    if isinstance(metadata, SurfaceMetadata):
        return metadata
    values = dict(metadata or {})
    if "range" in values:
        cut_range = values.pop("range")
    component_id = values.pop("component_id", None)
    component_name = values.pop("component_name", None)
    surface_role = values.pop("surface_role", None)
    component_role = values.pop("component_role", None)
    if component_id is not None and (
        component_name is None or surface_role is None or component_role is None
    ):
        try:
            component = component_for_id(component_id)
            if component_name is None:
                component_name = component.name
            if surface_role is None:
                surface_role = component.surface_role
            if component_role is None:
                component_role = component.role.value
        except ValueError:
            pass
    return SurfaceMetadata(
        cut_range=cut_range,
        normal=values.pop("normal", None),
        source=values.pop("source", None),
        grid=values.pop("grid", None),
        component_id=component_id,
        component_name=component_name,
        surface_role=surface_role,
        component_role=component_role,
        removed_by=values.pop("removed_by", None),
        tool_id=values.pop("tool_id", None),
        line_no=values.pop("line_no", None),
        operation_id=values.pop("operation_id", None),
        motion_type=values.pop("motion_type", None),
        source_line=values.pop("source_line", None),
        segment_index=values.pop("segment_index", None),
        segment_count=values.pop("segment_count", None),
        arc_center=values.pop("arc_center", None),
        arc_radius=values.pop("arc_radius", None),
        arc_direction=values.pop("arc_direction", None),
        collision_warning=bool(values.pop("collision_warning", False)),
        collision_component=values.pop("collision_component", None),
        collision_reason=values.pop("collision_reason", None),
        gouging_risk=bool(values.pop("gouging_risk", False)),
        sharp_edge=bool(values.pop("sharp_edge", False)),
    )


def component_labels(
    component_id: int | None,
) -> tuple[str | None, str | None]:
    if component_id is None:
        return None, None
    try:
        component = component_for_id(component_id)
    except ValueError:
        return None, None
    return component.name, component.surface_role
